version: '3.3'
services:
 nginx:
  image: 'nginx:latest'
  volumes:
   - {type: bind, source: ./nginx/nginx.conf, target: /etc/nginx/nginx.conf}
  ports:
   - {target: 80, published: 80, protocol: tcp}
  depends_on:
    - front-end
    - bank-app
    - textnum-gen
    - prize-gen
    - bankconsumer
    - activemq
    - mongo
  deploy:
   placement:
    constraints: [node.role == manager] 
 front-end:
  image: 'mcquiggan/frontend:latest'
  build:
   context: ./frontend
   dockerfile: Dockerfile
  ports:
   - {target: 3000, protocol: tcp}
 bank-app:
  image: 'mcquiggan/bankexample:latest'
  build:
   context: ./BankExample
   dockerfile: Dockerfile
  ports:
   - {target: 8080, protocol: tcp}
  depends_on:
    - activemq
 textnum-gen:
  image: 'mcquiggan/textnumgen:latest'
  build:
   context: ./TextNumGen
   dockerfile: Dockerfile
  ports:
   - {target: 8081, protocol: tcp}
  depends_on:
    - activemq
 prize-gen:
  image: 'mcquiggan/prizegen:latest'
  build:
   context: ./PrizeGen
   dockerfile: Dockerfile
  ports:
   - {target: 8082, protocol: tcp}
  depends_on:
    - activemq
 bankconsumer:
  image: 'mcquiggan/bankexampleconsumer:latest'
  build:
   context: ./BankExampleConsumer
   dockerfile: Dockerfile
  ports:
   - {target: 8084, protocol: tcp}
  depends_on:
    - activemq
 activemq:
  image: 'rmohr/activemq'
  ports:
   - {target: 8161, protocol: tcp, published: 8161}
   - {target: 61616, protocol: tcp}
  depends_on:
    - mongo
 mongo:
  image: 'mongo:latest'
  ports:
   - {target: 27017, protocol: tcp, published: 27017}
  deploy:
   placement:
    constraints: [node.role == manager]